version: "3"

services:
    webserver:
        build:
            context: ./docker/bin/${PHPVERSION}
        container_name: "${COMPOSE_PROJECT_NAME}-webserver"
        restart: "always"
        ports:
            - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
            - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
            - "${XDEBUG_PORT}:9003"
        links:
            - database
        volumes:
            - ${DOCUMENT_ROOT}:/var/www/html:rw
            - ${PHP_INI}:/usr/local/etc/php/php.ini
            - ${SSL_DIR}:/etc/apache2/ssl/
            - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
            - ${APACHE_LOG_DIR}:/var/log/apache2
            - ${XDEBUG_LOG_DIR}:/var/log/xdebug
        environment:
            APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
            PMA_PORT: ${HOST_MACHINE_PMA_PORT}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MYSQL_PORT}
            XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT}"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    database:
        build:
            context: "./docker/bin/${DATABASE}"
        container_name: "${COMPOSE_PROJECT_NAME}-database"
        restart: "always"
        ports:
            - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
        volumes:
            - ${MYSQL_INITDB_DIR}:/docker-entrypoint-initdb.d
            - ${MYSQL_DATA_DIR}:/var/lib/mysql
            - ${MYSQL_LOG_DIR}:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpmyadmin:
        image: phpmyadmin
        container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
        links:
            - database
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            UPLOAD_LIMIT: ${UPLOAD_LIMIT}
            MEMORY_LIMIT: ${MEMORY_LIMIT}
        ports:
            - "${HOST_MACHINE_PMA_PORT}:80"
            - "${HOST_MACHINE_PMA_SECURE_PORT}:443"
        volumes:
            - /sessions
            - ${PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

    redis:
        container_name: "${COMPOSE_PROJECT_NAME}-redis"
        image: redis:latest
        ports:
            - "127.0.0.1:${HOST_MACHINE_REDIS_PORT}:6379"
